FROM php:8.3.25-fpm-alpine3.21

# Install dependencies # PHP Modules #
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions redis exif gd zip soap imap bcmath ssh2 opcache sockets intl imagick @composer mysqli pdo_mysql
RUN apk add -U imagemagick ghostscript tzdata curl && rm -rf /var/cache/apk/*
